### ISSUE TITLE
ScaleIT login

### ISSUE THREAD

**Issue by Ccj-pro** [scaleit-i40/scaleit-ce-vm#3]
When I use the .bat file to install the vm, I am prompted to enter the password of the account. Should I register this account password?

**Comment by scaleit-i40** [comment]
Which password do you get prompted for? The Windows Administrator password for installation new software?

**Comment by Ccj-pro** [comment]
After running scalit-vm. Bat, I open scalit-ce vm, I enter the virtual machine, in the virtual machine, the following contents are displayed:

**Ubuntu 16.04.6 LTS ScaleIT tty1
ScaleIT login:**

What should I type in here?

**Comment by scaleit-i40** [comment]
Ok, I see. You don't need to login here. Just proceed as stated in the [readme section "Start von ScaleIT als Benutzer"](https://github.com/scaleit-i40/scaleit-ce-vm#start-von-scaleit-als-benutzer) and start your browser with 

    http://10.0.3.30

If you want to top your ScaleIT session just shutdown the virtualbox machine and you're done. You can restart it later and continue your ScaleIT experiences.

**Comment by Ccj-pro** [comment]
When I open the virtual machine, I just have to go to http://10.0.3.30 in my Windows browser, right?
I tried it on my computer, but the address was not accessible.

The following information is displayed on the page。

This site can’t be reached 10.0.3.30 refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

**Comment by scaleit-i40** [comment]
Maybe your network settings are not set correctly.

Here are the network settings to access the ScaleIT VM from your PC's browser:

https://github.com/scaleit-i40/scaleit-ce-vm#details-zum-virtualbox-image

**Comment by WeeSee** [comment]
Solution:

Please run the setup-script ```Install-Scaleit-VM.bat``` **as Administrator on the command console** (not with a mouse click from the WIndows Explorer!).

**Comment by scaleit-i40** [comment]
closed due to inactivity
